######################################################################
# Automatically generated by qmake (3.0) Thu Dec 28 13:13:14 2017
######################################################################

TEMPLATE = app
TARGET = ElfMApp
INCLUDEPATH += .

QT += multimedia

# Input
SOURCES += main.cpp \
    command_reader.cpp \
    player.cpp

HEADERS += \
    command_reader.h \
    player.h
