######################################################################
# Automatically generated by qmake (3.0) Thu Dec 28 13:13:14 2017
######################################################################

TEMPLATE = app
TARGET = ElfMApp
INCLUDEPATH += .

# Input
SOURCES += main.cpp

HEADERS += \
    cli_main.h
